# -*- coding: utf-8 -*-
"""Customer Risk Intelligence.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gkQVJyku53GLuqmOBcQLA1aVJ0GJoEdE

# Customer Risk Intelligence: A Churn Prediction and Retention Prioritization Framework

# DESCRIPTION

Customer churn poses a significant challenge for businesses, as retaining existing customers is often more cost-effective than acquiring new ones. This project develops a data-driven approach to identify customers at risk of churning and prioritize retention efforts based on their business value.

Using transactional retail data, customer behavior is first analyzed through RFM (Recency, Frequency, Monetary) analysis to understand purchasing patterns. A Customer Value Score (CVS) is then constructed to estimate the relative importance of each customer to the business.

To predict churn risk, a Random Forest classifier is trained using behavioral features such as purchase frequency, total spending, and average order value. Recency-based features are intentionally excluded from the model to avoid data leakage, as churn is defined using a recency threshold.

The model achieves ~70% test accuracy and a ROC-AUC score of ~0.73, indicating moderate predictive capability in identifying churn-risk customers based on behavioral patterns.

Beyond prediction, the project focuses on actionable business insights by combining churn probability with customer value to identify high-value customers at high risk of churn. These customers represent priority targets for retention campaigns.

**The final output of this analysis includes**:

A churn prediction model based on customer behavior

Feature importance analysis to identify drivers of churn

Risk–value segmentation of customers

Identification of the top 20% highest-risk customers

A revenue-at-risk analysis to estimate potential financial exposure

This framework demonstrates how machine learning can be integrated with customer analytics to support data-driven retention strategies and revenue protection.

#How This Project Differs from Conventional Churn Models

**Beyond prediction accuracy**: Most churn projects focus only on predicting churn, while this project links churn probability with customer value to prioritize retention decisions.

**Business-first framework**: Instead of treating churn purely as a classification problem, the analysis identifies high-value customers at high risk, enabling targeted retention strategies.

**Revenue impact estimation**: The model output is combined with customer spending data to estimate revenue exposure from high-risk customers, connecting machine learning results to real business outcomes.

# KEY FINDINGS

1.Customer spending behavior is the strongest predictor of churn risk.

2.The Random Forest model achieved ~70% accuracy and 0.73 ROC-AUC while avoiding recency-based data leakage.

3.The model correctly identifies ~74% of churn-risk customers.

4.The top 20% highest-risk customers represent a significant share of revenue exposure, indicating that targeted retention campaigns should prioritize this segment.

# PROJECT PIPELINE

Transaction Data

Customer Behavior Modeling (RFM)
       
Customer Value Scoring
       
Risk–Value Segmentation
       
Random Forest Churn Prediction
       
Feature Importance & Business Insights

Revenue at risk

Retention strategy
"""

import pandas as pd

from google.colab import drive
drive.mount('/content/drive')

file_path="/content/drive/MyDrive/online_retail_II.xlsx"


df1=pd.read_excel(file_path,sheet_name='Year 2009-2010')
df2=pd.read_excel(file_path, sheet_name='Year 2010-2011')
df=pd.concat([df1,df2])

df.describe()

df.shape

df.info()

df.head(100)

#finding the extent of null values in the dataset

df.isnull().sum()

type(df) #dataframe overwritten

df=df.dropna() #remove missing cutomerid and descriptions

df.isnull().sum()

#convert datatypes into into
df['Customer ID']=df['Customer ID'].astype(int)

#remove orders that were cancelled

df=df[~df['Invoice'].astype(str).str.startswith('C')]

#removing negative values

df=df[(df['Quantity']>0) & (df['Price']>0)]

df['InvoiceDate']=pd.to_datetime(df['InvoiceDate'])

#without datetime frequency and recency cannot be calculated

#create total purchase work

df['Total Purchase']=df['Quantity']*df['Price']

df.describe()

#max quantity and max price are outliers

from os.path import exists
import os

os.makedirs('/content/drive/MyDrive/churn_project', exist_ok=True)
df.to_pickle('/content/drive/MyDrive/churn_project/cleaned.pkl')

df = pd.read_pickle('/content/drive/MyDrive/churn_project/cleaned.pkl')

#RFM Analysis

#creating a snapshot date (reference date)

snapshot_date=df['InvoiceDate'].max()+pd.Timedelta(days=1)

#creating an RFM frame

rfm=df.groupby('Customer ID').agg({

    "InvoiceDate": lambda x: (snapshot_date-x.max()).days,
    "Invoice":'nunique',
    "Total Purchase":'sum'
})

#renaming the columns

rfm.columns=["Recency", "Frequency","Monetary Value"]

rfm.head(100)

rfm.shape

#Data has been transformed successfully

rfm.describe()


#params: frequenc>0, min and max days make sense, all positive MValues

#rfm checkpoint

rfm.to_pickle('/content/drive/MyDrive/churn_project/rfm.pkl')

print((rfm['Frequency']==1).mean())


#Observations:
#from the data description, the min values are too low for each case
#27% of customers never return after buying from this store once, thats 1/4 customers
#the store is good at acquiring customers but very bad at retaining them, maybe due to their limited products or high prices (Due to the min monetary value being low)

#Churning logic
# not purchased anything > 90 days= churned


rfm["Churn"]=(rfm['Frequency']>120).astype(int)

print(rfm['Churn'].value_counts())

#normalize frequency and recency

rfm['Frequency_norm']=(rfm["Frequency"]/rfm["Frequency"].max())

rfm["Recency_norm"]=(1-rfm["Recency"]/rfm["Recency"].max()) #inverting recency so that high score=high engagement

rfm['Frequency_norm'].head()

rfm['Recency_norm'].head()

# Engagement score logic

rfm['Engagement Score']= (0.6* rfm["Frequency_norm"]+ 0.4*rfm['Recency_norm'])

rfm['Engagement Score'].head()

# Customer Value score (CVS)

rfm['CVS']=rfm['Monetary Value']*rfm['Engagement Score']

rfm["CVS"].head()

# 0: customer not churned; active
# 1 :customer churned; churned

rfm['Recency'].describe()

rfm.sort_values("Recency", ascending=False).head()

(rfm["Recency"] > 120).mean()

rfm["Churn"] = (rfm["Recency"] > 120).astype(int)

rfm["Churn"].value_counts(normalize=True)

rfm["Frequency_norm"] = rfm["Frequency"] / rfm["Frequency"].max()

rfm["Recency_norm"] = 1 - (rfm["Recency"] / rfm["Recency"].max())

rfm["Frequency_norm"].head()

print(rfm["CVS"].describe())

print(rfm['Engagement Score'].describe())

rfm.shape

rfm.to_pickle(
    '/content/drive/MyDrive/churn_project/rfm_final.pkl'
)

df=pd.read_pickle('/content/drive/MyDrive/churn_project/rfm_final.pkl')

df.head()

# RISK VS STRATEGY MATRIX


#Creating value matrix


rfm['ValueSegment']=pd.qcut(

      rfm['CVS'], q=3, labels=['Low Value', 'Medium Value', 'High Value']

)

# creating risk segments

rfm['RiskSegment']=rfm['Churn'].map({0: 'Low Risk', 1:'High Risk'})

#create the matrix

strategy_matrix=pd.crosstab(
    rfm['ValueSegment'],

    rfm['RiskSegment']


)
print(strategy_matrix)

import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(8,5))

sns.scatterplot(
    x="CVS",
    y="Recency",
    hue="RiskSegment",
    data=rfm,
    alpha=0.6
)

plt.title("Customer Risk vs Value Distribution")
plt.show()

rfm.groupby("ValueSegment")["Churn"].mean() *100


#churn rate across segments vvimp

# Observations:
#low value customers leave early as compared to high value customers
#The bussiness is doing fine by that metric, so it is a retention problem??

# 27% customers were likely to churn faster, those people might fall into this category of low val+high churn; The hypothesis was correct

rfm.to_pickle('/content/drive/MyDrive/churn_project/rfm_strategy_ready.pkl')

df=pd.read_pickle('/content/drive/MyDrive/churn_project/rfm_strategy_ready.pkl')

#vizualization

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(8,6))

sns.scatterplot(
    data=rfm,
    x="CVS",
    y="Recency",
    hue="RiskSegment",
    alpha=0.6
)

value_median=rfm["CVS"].median()
recency_median=rfm["Recency"].median()


plt.xscale('log')
plt.axvline(value_median, linestyle="--")
plt.axhline(recency_median, linestyle="--")





#labelling the quadrants

# quadrant labels (axis-relative positions)

plt.text(0.05, 0.85,
         "Low Value\nHigh Risk\n(Auto campaigns)",
         transform=plt.gca().transAxes,
         fontsize=11)

plt.text(0.65, 0.85,
         "High Value\nHigh Risk\n(PRIORITY RETENTION)",
         transform=plt.gca().transAxes,
         fontsize=11)

plt.text(0.05, 0.15,
         "Low Value\nLow Risk\n(Low priority)",
         transform=plt.gca().transAxes,
         fontsize=11)

plt.text(0.65, 0.15,
         "High Value\nLow Risk\n(Loyal customers)",
         transform=plt.gca().transAxes,
         fontsize=11)

plt.title("Customer Risk vs Value Matrix")
plt.xlabel("Customer Value Score")
plt.ylabel("Recency (Days Since Last Purchase)")

plt.show()

#customer value distribution plot
#Proof of the 80/20 rule being applicable in this case

plt.figure(figsize=(8,5))

sns.histplot(rfm["CVS"], bins=50)

plt.xscale("log")

plt.title("Distribution of Customer Value Scores")
plt.xlabel("Customer Value Score (Log Scale)")
plt.ylabel("Number of Customers")

plt.show()

rfm['AvgOrderval']=rfm['Monetary Value']/rfm['Frequency']

# ML part

#features on which we base our models
X=rfm[['Frequency','Monetary Value','AvgOrderval']]
y=rfm['Churn']

#test train split
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

# training a random forest model to make predictions

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

rf_model=RandomForestClassifier(n_estimators=1500, max_depth=18,min_samples_split=10,min_samples_leaf=3,max_features="sqrt", random_state=42)

rf_model.fit(X_train,y_train)

#make predictions
y_predict=rf_model.predict(X_test)

y_predict

accuracy=accuracy_score(y_test,y_predict)
print(accuracy)

#cross validation

from sklearn.model_selection import cross_val_score

cross_val_scores=cross_val_score(rf_model,X,y,cv=5)
print("CV Scores:", cross_val_scores)
print("Average CV Accuracy:", cross_val_scores.mean())

#checking for overfitting

train_accuracy=rf_model.score(X_train,y_train)
test_accuracy=rf_model.score(X_test,y_test)

print(train_accuracy)
print(test_accuracy)

#Precision: How often the churn predictions are correct
#recall: How many churners were correctly identified by the model

#classification report

from sklearn.metrics import classification_report

print(classification_report(y_test,y_predict))

#confusion matrix
from sklearn.metrics import confusion_matrix

confusion_matrix(y_test,y_predict)

#ROC AUC: How well the model is able to tell the difference between churners vs non churners

from sklearn.metrics import roc_auc_score
y_prob = rf_model.predict_proba(X_test)[:,1]
roc_auc=roc_auc_score(y_test,y_prob)

print("ROC_AUC score:" ,roc_auc)

import pandas as pd

importance = pd.Series(
    rf_model.feature_importances_,
    index=X.columns
).sort_values(ascending=False)

print(importance)

#Spending behavior (total spend and order value) is a stronger predictor of churn than purchase frequency
# suggesting that customer value signals are key indicators of long-term retention.

# Post model step; Finding out which customers are worth chasing

rfm['churn_prob']=rf_model.predict_proba(X)[:,1]

rfm_sorted = rfm.sort_values("churn_prob", ascending=False)

rfm_sorted

#Customer Ranks

rfm_sorted[[ 'churn_prob']].head()

#finding out the top 20% in terms of risk

top_risk=rfm.sort_values("churn_prob", ascending=False).head(int(0.2*len(rfm)))

top_risk

#filtering the high value customers from the top 20%

vip_risk_customers = top_risk[top_risk["ValueSegment"] == "High Value"
]

print(vip_risk_customers.head())
print("No of At risk customers:",len(vip_risk_customers))

#revenue at risk

vip_revenue=vip_risk_customers['Monetary Value'].sum()
print("Revenue at risk:", vip_revenue)

#which customers to target first

print("Target the customers in the following order")

vip_risk_customers = vip_risk_customers.sort_values(
    "churn_prob",
    ascending=False
)

vip_risk_customers

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(10,7))

sns.scatterplot(
    data=rfm,
    x="Monetary Value",
    y="churn_prob",
    hue="ValueSegment",
    alpha=0.7
)

#highlighting the vips

sns.scatterplot(

  data=vip_risk_customers,
  x="Monetary Value",
  y="churn_prob",
  color="black",
  marker="x",
  s=80,
  label="VIPs"
)
plt.xscale('log')
plt.axhline(rfm["churn_prob"].quantile(0.80), linestyle="--")
plt.axvline(rfm["Monetary Value"].median(), linestyle="--")

plt.xlabel("Customer Value (Monetary)")
plt.ylabel("Churn Probability")
plt.title("Customer Risk vs Value Prioritization")
plt.legend()
plt.show()

#The black X shows high value high risk customers

"""Customers highlighted in black represent high-value customers with churn probability above the 80th percentile. These customers are priority targets for retention campaigns due to their high revenue contribution and elevated churn risk."""

#Revenue at risk calculations


rfm_sorted=rfm.sort_values("churn_prob", ascending=False)

rfm_sorted['cumulative_revenue']=rfm_sorted['Monetary Value'].cumsum()
rfm_sorted['customer_percentile']=(
    range(1,len(rfm_sorted)+1)

)
rfm_sorted['customer_percentile']=rfm_sorted['customer_percentile']/rfm_sorted['customer_percentile'].max()

import matplotlib.pyplot as plt

plt.figure(figsize=(10,6))

plt.plot(
    rfm_sorted["customer_percentile"],
    rfm_sorted["cumulative_revenue"]
)

plt.axvline(0.20, linestyle="--", color="red", label="Top 20% Risk Customers")

plt.xlabel("Customer Percentile (Ranked by Churn Risk)")
plt.ylabel("Cumulative Revenue")
plt.title("Revenue Exposure from High-Risk Customers")

plt.legend()
plt.show()

top20 = rfm_sorted.head(int(0.2 * len(rfm_sorted)))

revenue_at_risk = top20["Monetary Value"].sum()
total_revenue = rfm["Monetary Value"].sum()

print("Revenue at Risk:", revenue_at_risk)
print("Share of Revenue:", revenue_at_risk / total_revenue)